### ISSUE TITLE
Delete custom shelf

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#237]
**Describe the solution you'd like**
Add the option of deleting a custom shelf. 

The confirmation dialog should be used to ask the user whether they are sure they want to delete the custom shelf. The books in this shelf should not be deleted as they should still appear in a predefined shelf.

**Comment by knjk04** [comment]
Blocked by issue #92

**Comment by MikeLowrie** [comment]
Mind if I pick up this issue?

**Comment by knjk04** [comment]
Not at all, thanks a lot! Could you also write some accompanying tests (e.g. test that clicking the button actually deletes a custom shelf and testing that deleting a custom shelf does not remove any of the books or authors)?

**Comment by MikeLowrie** [comment]
Sure thing, I'll jump into that once done with #253.

**Comment by MikeLowrie** [comment]
So I had two concepts for how to allow a user to delete a shelf, feel free to offer feedback on which you have a preference for.

Idea A: Deleting a shelf:
 - Only allow deleting a custom shelf, all four standard shelves won't be allowed for delete
 - Button next to "Add book" on home screen appears when user selects a custom shelf, "Delete shelf"
 - Warning box to confirm delete with "Are you sure you want to delete this shelf?"
 - Might be challenging to constantly update home screen based on shelf selected, but would likely be faster solution

Idea B: Delete through Edit
 - Allow users to edit a selected shelf, possibly even the "default" shelves
 - "Delete Shelf" would be visible in "Edit Shelf" dialog rather than on home screen
 - "Edit Shelf" button would always be visible from the home screen, rather than dynamically showing/hiding like the "Delete Shelf" in the first solution

**Comment by knjk04** [comment]
I like the edit shelf idea (it can be extended later to also include renaming shelves). However, the predefined shelves should never be deleted.

Perhaps we could have a dropdown in the edit shelf dialog that only shows the custom shelves. What do you think?

**Comment by MikeLowrie** [comment]
So going with Idea B:
- Users can click "Edit Shelf", with a button next to "Add book".
- Button will only be enabled if there are custom shelves in the current data.
- Clicking on the button will pop up a dialog similar to "Add shelf", but with a dropdown along the top-left of the dialog to select a specific shelf. This will allow users to adjust the Name field through Edit.
- The dialog will have "Delete Shelf" in red, and "Save" and "Close" in normal blue along the bottom.

I think that's feasible. It will be valuable to find the right way to re-use the Add Shelf dialog for this, and allowing the Name to be adjusted here also helps knock out #296 as well.
