### ISSUE TITLE
Unable to add a new shelf

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#243]
**Describe the bug**

The 'save' button in the custom shelf form is greyed out, so a new shelf cannot be added.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Click on 'add shelf'
3. Enter in a name for the shelf that is not already in use
4. Press save
5. Click on 'add shelf'
6. Enter in a name that is not already used for a shelf (predefined or custom)
7. See error

**Expected behaviour**

The save button should not be greyed out and the new shelf should be added.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/90153786-4e283900-dd81-11ea-80a7-6a07ed62d1c0.png)

**Comment by knjk04** [comment]
We need to find the exact reproduction steps as this bug does not always manifest

**Comment by amit1307** [comment]
I was able to replicate it, can you try the below steps:

1. Add a new shelf that doesn't exist and save it.
2. Try adding another shelf and in the shelf name type the name of the shelf that was added in step 1.
3. Click on the save button (actually the save button should have been disabled because the shelf name text field gives an error).
4. Once the button is clicked, it gets disabled and never gets enabled. Only the page refresh makes it enable.

Seems like the greyed out state never gets cleared or something. If you think this is the issue, I can have a look at it?

**Comment by knjk04** [comment]
@amit1307 Sorry, I missed this.

I haven't been able to reproduce it. I can't get past step 2 as the 'save' button is greyed out for me. Would it be possible for you to try again on the latest version of master?

**Comment by knjk04** [comment]
@amit1307 Did you get a chance to try this on master?

**Comment by knjk04** [comment]
(Discussed privately. This should be fixed now)
