### ISSUE TITLE
Refactor BookForm

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#249]
`BookForm` is a large class that could be split into smaller classes to make it easier to maintain.

For a recent example of some good refactoring, see #203

**Comment by kaansonmezoz** [comment]
Hello again :slightly_smiling_face: 
Can I take this issue ?

**Comment by knjk04** [comment]
Sure, that would be great. Thanks!

**Comment by knjk04** [comment]
I'm going to block this issue temporarily until #254 is fixed. I hope this does not cause any inconvenience. I'll let you know when this issue gets unblocked

**Comment by knjk04** [comment]
Unblocked. I've fixed #254

**Comment by knjk04** [comment]
How are you getting on with this?

**Comment by kaansonmezoz** [comment]
I've been working on this for some time. Today I committed some of my work. It's not finished :slightly_smiling_face:

**Comment by knjk04** [comment]
OK, that's fine. Feel free to open a draft PR if you would like any early feedback. 

Also, if you're not level with master, could you please rebase as we have made a few changes to the `BookForm`?

**Comment by kaansonmezoz** [comment]
Early feedback is a great idea. And it will also reduce the number of commits that must be reviewed when I open the PR :slightly_smiling_face:  I've also noticed some classes needs refactoring too because of breaking the SOLID principles. I will open their issues so that you could decide whether it should be refactored :slightly_smiling_face: 

I've rebased my fork's master then merged it :slightly_smiling_face:

**Comment by knjk04** [comment]
>  I've also noticed some classes needs refactoring too because of breaking the SOLID principles. I will open their issues so that you could decide whether it should be refactored 🙂

Thanks, that would be great!
