### ISSUE TITLE
Add button (shelf form) not initially greyed out

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#255]
**Describe the bug**

The add button in the shelf form is not initially greyed out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Click on 'add shelf'
3. See error

**Expected behaviour**

The add button should initially be greyed out until a valid shelf name (unique and not empty) is provided.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/90307856-593eae80-ded2-11ea-86e0-58837fa9c9e9.png)

**Comment by inhundreds** [comment]
Hi Karan, can I work on this? I think it is related to #243.

**Comment by knjk04** [comment]
Hi, sure, I'll assign you to the issue. Thanks!

**Comment by inhundreds** [comment]
I think that there are 3 problems related to the save button:
1. by default, the button is enabled when created even if the textfield is empty;
2. the binder validates  using the default ValueChangeMode of the textfield; the default change mode is [ON_CHANGE](https://vaadin.com/api/platform/14.3.4/com/vaadin/flow/component/textfield/TextField.html#getValueChangeMode--); it means that the synchronization happens when the value is [commited](https://vaadin.com/api/platform/14.3.4/com/vaadin/flow/data/value/ValueChangeMode.html#ON_CHANGE)
3. when the form is closed, the textfield is not cleaned;

I think that 2nd and 3rd point causes issue #243 

For the solution: 
- the 1st point is easy;
- the 2nd point I think it can be resolved modifying the value change mode;
- for the 3rd point: I can change the behaviour; is it ok to do that in this issue?

Thanks, 
Diego

**Comment by knjk04** [comment]
Yes, that's fine. Feel free to also fix the 3rd point. Thanks!

**Comment by inhundreds** [comment]
Hello Karan, just a question about the 3rd point: do you expect the textfield to be cleared when the user saves the shelf and also when he clicks outside the dialog closing it without saving?

**Comment by knjk04** [comment]
Yes, the clear button should be closed in both cases. If a user clicks outside the dialog, we should treat that as a cancel operation
