### ISSUE TITLE
Missing development setup instructions

### ISSUE THREAD

**Issue by tomglk** [Project-Books/book-project#304]
**Missing development setup instructions**

The readme only contains information on how to setup for production.

**Expected behaviour**

There should also be a section describing how to setup for development.

Containing information like:
- start the database and php admin console with "docker-compose up mysql phpmyadmin"
- use profile "dev" in the run-config of intellij
- start the app through intellij

The eclipse equivalents of the intellij setup / startup should also be added.

**Comment by knjk04** [comment]
Thanks for bringing this up.

> The eclipse equivalents of the intellij setup / startup should also be added.

Sorry, what do you mean by this?

**Comment by Tom-private** [comment]
I described how that the profile in the IntelliJ run-config has to be set.
Because eclipse is mentioned in the setup,we should add the corresponding instructions for eclipse's equivalent of the run-config. (Maybe eclipse uses the same naming, maybe there is a special name, I never used eclipse, so I don't know.)

**Comment by knjk04** [comment]
Sorry, I missed this. Thanks for this

**Comment by knjk04** [comment]
No longer relevant
