### ISSUE TITLE
Fix Vaadin live reload

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#407]
![image](https://user-images.githubusercontent.com/11173328/95009904-4a948e00-061d-11eb-8f8d-0684b77c50e0.png)

Vaadin live reload does not currently work. This can make development a lot slower.

**Comment by knjk04** [comment]
@TomGilke2468 I seem to recall that you managed to come up with a solution for this. Is that correct?

**Comment by Tom-private** [comment]
Hi @knjk04 ,
no, sadly not. I have never seen that issue.
The thing that you may recall is, that I had issues with using the app in docker while working on the frontend, because a rebuild of the project didn't seem to project the changes to the CSS.
My solution for that was to only start the database in docker and run the app directly in IntelliJ.

**Comment by dmitraver** [comment]
I could look into this one.

**Comment by knjk04** [comment]
@dmitraver Sure, thanks!
