### ISSUE TITLE
Fix bad credentials exception being thrown

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#585]
**Describe the bug**

After sending a POST request to the `register` endpoint with only valid email and password, the server sends back `403 Forbidden` with `BadCredentialsException` in the body

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app
2. Send a POST request (e.g. with Postman) to `http://localhost:8080/api/register` with only a valid email and password in the body
3. See error

**Expected behaviour**

A success status code (e.g. `200 OK`) is returned.

**Additional context**

This is on the `0.2.0` branch.

Sample body (JSON):

```json
{
    "email": "remus@werewolf.com",
    "password": "083540sdfljksj"
}
```

Even though 403 is returned, a new user is created in the database.

**Comment by osopromadze** [comment]
Hey @knjk04, I would like to work on this issue.

**Comment by knjk04** [comment]
Hi @osopromadze, thanks! I'll assign you to it

**Comment by osopromadze** [comment]
I doubt about one thing. In [```UserService.java```](https://github.com/Project-Books/book-project/blob/0.2.0/backend/src/main/java/com/karankumar/bookproject/backend/service/UserService.java#L86) we have a line where the user is authenticating after a successful registration. I was thinking why it is needed? Will not be better to just register and that's all? Because it is causing problems too.

```java
userRepository.save(userToRegister);

authenticateUser(user);
```

As you said *'Even though 403 is returned, a new user is created in the database.'*. This is happening because of one thing. As you know it is allowed to register only by email and in this case, the username is set to NULL, so after successful registration, it is trying to authenticate with username and password but throwing ```BadCredentialsException``` because the username is ```null```.

So there are some solutions:

1. Remove the line where we are calling the method to authenticate the user.
2. Don't allow to register without a username.
3. Allow to register without a username and take the first part of the email as temporary to be able to authenticate with it.

If you have any suggestions please let me know.

**Comment by knjk04** [comment]
@osopromadze Thanks for bringing this up. 

I can see where you're coming from. It may seem like a user shouldn't need to be authenticated if they were able to register successfully. I would need to check whether this affects issuing a JWT after registering (or perhaps you can check if you'd like).

We wanted to allow a user to sign up either with a username or an email address. I'll double-check this, though, as we may remove the username option. I'll get back to you on this shortly

**Comment by knjk04** [comment]
@osopromadze We've removed signing up with a username. I tried signing up with an email address and we don't get the 403. Could you also check this on your end to make sure this works as expected?

**Comment by osopromadze** [comment]
Ok @knjk04, I will check it

**Comment by knjk04** [comment]
@osopromadze 

Update: I've integrated the signup page (`localhost:3000/sign-up`) to the backend and we still get a 403. This time, however, the server does not create the new user. I think this is because the server expects a JWT. This is still a bug, though, because, as you may already know, the server should only have issued a JWT after having authenticated the user
