### ISSUE TITLE
Order books in 'to read'

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#63]
**Describe the solution you'd like**

Be able to specify an order in the 'to read' shelf of the list of books that you want to most read (the lower the number the more you want to read it).

**Comment by Jumismo** [comment]
Could I take this issue?

**Comment by knjk04** [comment]
Sure. I've updated the issue description as I don't think having an `int` field is the best way to go about it.

Before I assign you to the issue, could you first describe your implementation approach?

**Comment by anotherfathead** [comment]
Hi, If this issue is available I'd like to work it.

**Comment by knjk04** [comment]
Sure. Before I assign you to the issue, could you please first describe your implementation approach?

**Comment by anotherfathead** [comment]
Unknown: 
- Does the scope of this issue include updating the user interface to include:
  - the ability to reorder the 'to read' shelf? 
  - the 'sort by my priority' option? 

Task Assumptions:
-  User can order/reorder books in their 'to read' list as often as they choose
-  The order given by the user is the book's 'to read' ranking
  - Lower the 'rank' the higher up the list it appears. 
-  A book's 'to read' ranking must be persisted

Approach: 
- initial idea is a minimal implementation of Jira's LexoRank algorithm or similar Library sort algorithm
  - instead of an int, or similar, use alaphnumerics for sorting with gaps between 
- update book rank based on user's ordering of book in 'to read' list
  - update ranking of books affected by the re-ranking of a book in the 'to read' list
-  add corresponding updates to the data models and database to persist the book's 'to read' rank

**Comment by knjk04** [comment]
@anotherfathead I'm very sorry for the delay in getting back to you. I thought I had responded to this

> Does the scope of this issue include updating the user interface

No, just the backend

> Task Assumptions:

All are correct

> Approach

That seems good to me! 

Unfortunately, as there's only a week left before the end of the month, we may not be able to get your PR merged in before the 31st, so I'll remove the 'hacktoberfest' label. Would you still be interested in working on this?

**Comment by abhity16** [comment]
Hi, 
If it's still open, I'd like to work upon this.

**Comment by knjk04** [comment]
Hi @abhity16,

Thanks for your interest in this. I'm going to block this temporarily until we're ready to implement this on the frontend.

**Comment by priya1712d** [comment]
Hi, @knjk04  Could I work on this issue?

**Comment by knjk04** [comment]
Hi @priya1712d, we only assign at most one issue at a time to new contributors (see https://project-books.github.io/docs/development/contributing/#new-contributors-assigned-to-at-most-one-issue-at-a-time in our contributing document). Once you've completed your currently assigned issue, if this issue is still available, you are free to work on this if you are still interested
