### ISSUE TITLE
Add JWT token to header in API requests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#722]
**Describe the solution you'd like**
In every API call apart from logging in and signing up (e.g. deleting an account), we should safely store the JWT token we receive after logging in. Then, we need to send it on every subsequent request in the header.

Check this works as intended by running the server

**Comment by RivaD2** [comment]
@knjk04 can you assign me this ticket? :) When I open the issue, I am unable to assign myself for some reason.(Perhaps some sort of setting is not enabled etc.)

**Comment by RivaD2** [comment]
Here's what I'm thinking for the approach:

**1st pt of this: Safely storing the token, quick breakdown for the frontend**
- I have to first extract token  from the response
- Store access token in memory/set HTTP header by using token from memory variable.
( Refresh tokens would need to be used to renew access/implement a silent refresh so that the user doesn't have to keep re-authenticating every time the token expires. )
- Storing it in memory means I can send it header of every request (in `SendLoginRequest()` method in `Login.tsx`. 
- Before the previous token expires,  frontend makes request to `/refreshtoken` endpoint, along with the refresh token in cookie, which would send back a NEW refresh token to be used on other requests. 
- Frontend checks if user is logged in by seeing if the JWT variable is set/JWT is in memory
 - If no JWT exists in memory, the silent refresh should kick in
    
 **2nd part of this approach: What the backend needs to do**

 - The server would provide the JWT token (which it is already doing) AND a refresh token on login
 - A refresh token should be set by server to the client as an `HttpOnly` cookie along with proper flags for security. The JWT and the refresh token are sent to the client in the payload.
 - Server reads the httpCookie and if it finds a valid token, then it returns a new jwt token and a new refresh token to the client and sets a new refresh cookie via Set-cookie header.

Let me know if it is possible to implement the refresh token logic on the backend. If not, I can come up with another way to tackle this.

**Comment by RivaD2** [comment]
@knjk04 I closed this as PR was merged 👍

**Comment by knjk04** [comment]
@RivaD2 Thanks! We may need to also do this for creating a new shelf?

**Comment by RivaD2** [comment]
@knjk04 Ok cool! I will take this one first then 👍

**Comment by RivaD2** [comment]
> @RivaD2 Thanks! We may need to also do this for creating a new shelf?

I think will start with integrating JWT for creating new shelf then first. I can reopen this ticket (unless we want to make a new ticket for token integration for shelf).

 Is there anything in particular I need to know before I start (is there anything different for creating new shelf etc. vs login and delete?)

Thank you for your help!

**Comment by knjk04** [comment]
Great, thanks! I don't think so, this should be the same and relatively straightforward

**Comment by RivaD2** [comment]
@knjk04 Hey there Karan, the tokens are built in to the HTTPClient so anytime we make a new endpoint, they will already be included. When we build the functionality for adding the shelf, the token will be included already.

I'm gonna close this ticket and move on to list view ticket.

 If there are other endpoints that already exist that are not using the HTTPClient then we can create a new ticket for completing that. Does that sound like a good plan?
