### ISSUE TITLE
Where to find the .exe version of book-project for windows 

### ISSUE THREAD

**Issue by rudrakshkarpe** [Project-Books/book-project#984]
I am looking forward to using this on the windows machine, it seems an interesting project to make my reading habit even more strong but I am unable to find the exact .exe after downloading zip files from releases. 
please let me know if there's any such facility available for the same

**Comment by knjk04** [comment]
Hi @dyannya, apologies for the very late response in getting back to you.

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. 

We haven't released the,is and this is definitely not ready to be used. It's still a working prototype. If you still want to run it locally, you can follow the README instructions. This is intended for development. (Since this is a web app, we weren't planning to create a .exe file).
